### ISSUE TITLE
Limitations on packaging for use with Electron JS

### ISSUE THREAD

**Issue by LizanLycan** [nuintun/node-adodb#36] opened 2017-06-27 11:54 UTC
In development with Electron JS works perfectly. But after being packaged with `.asar` format it stops working completely. There are certain limitations: https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md#limitations-of-the-node-api . 

In 'lib': https://github.com/nuintun/node-adodb/blob/master/lib/proxy.js, there is a call to `.spawn` process. Is there a way to change this process to one accepted by Electron with `.asar`? I'm dealing with `execFile`, comment results. Maybe it could be something else I'm missing out on 

![image](https://user-images.githubusercontent.com/15185582/27586286-b9d95f02-5b0d-11e7-86cc-9072de285bc7.png)

**Comment by nuintun** [comment] 2017-06-30 02:12
I think this problem is caused by the BOM of UTF8, you can change this [L36](https://github.com/nuintun/node-adodb/blob/master/lib/proxy.js#L36) and test it.

```js
data = decodeURI(String(data));
```
Change to:
```js
data = decodeURI(String(data)).trim();
```

![qq 20170630100655](https://user-images.githubusercontent.com/1730277/27718132-63779e3c-5d7c-11e7-846a-b290614a0672.png)
![qq 20170630100945](https://user-images.githubusercontent.com/1730277/27718138-65bbe07c-5d7c-11e7-9ab8-9e6c9286d3cb.png)

If this problem I will fixed in next version.

**Comment by LizanLycan** [comment] 2017-06-30 02:15
Ok, I will try it

**Comment by deathgrindfreak** [comment] 2017-07-06 19:51
This error actually occurs when proxy.js tries to load in the adodb.js file.  You'll have to exclude the adodb.js from the asar and probably use [this library](https://github.com/epsitec-sa/hazardous) in order to ensure that the path is correct to the script.

**Closed** 2017-08-10 06:56 UTC
